[general]
ocr_model_path = "./"
db_path = "./db/paper.db"
forms = [ "f1", "f2", "f3", "f4", "f5", "f6",]
subjects = [ "chin", "eng", "math", "phy", "chem", "bio", "cs", "econ", "bafs", "ict", "hist", "chist", "clit", "m2",]
paper_path = "./db/papers/"
markdown_path = "./db/md/"
reports_path = "./reports/"

["paddle ocr"]
